# Generated by Django 4.2.6 on 2023-10-28 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField()),
                ('org_name', models.CharField(max_length=10000)),
                ('org_email', models.EmailField(max_length=10000, unique=True)),
                ('org_profileImg', models.ImageField(upload_to='uploads/org_profile')),
                ('org_address', models.TextField(max_length=10000)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('othername', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('contact_address', models.CharField(max_length=1000)),
                ('nin_number', models.IntegerField()),
                ('qualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('cover_letter', models.FileField(blank=True, upload_to='uploads/documents')),
                ('resume', models.FileField(blank=True, upload_to='uploads/documents')),
                ('ref_fullname', models.CharField(max_length=1000)),
                ('ref_phone_number', models.CharField(max_length=1000)),
                ('ref_address', models.CharField(max_length=1000)),
                ('work_auth', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary_exp', models.CharField(blank=True, max_length=1000, null=True)),
                ('availabilty', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, max_length=1000, null=True)),
                ('doc_files', models.FileField(upload_to='uploads/documents')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organizationprofile')),
            ],
        ),
    ]
