# Generated by Django 4.2.6 on 2023-11-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdata',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='org_email',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.organizationprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='email',
            field=models.CharField(default=1, max_length=225, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='org_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='org_address',
            field=models.TextField(max_length=1000),
        ),
    ]
